language: java
sudo: false
jdk:
  - oraclejdk8

services:
  - mysql

git:
  depth: 3 #clone repository to a maximum depth of 3 commits

before_install:
  - mysql -e 'CREATE DATABASE library;' #create table to execute tests

script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"

after_success:
  - mvn clean test jacoco:report coveralls:report #generate Jacoco reports
