language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE library;'

script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"

after_success:
  - mvn clean test jacoco:report coveralls:report
